# Generated by Django 2.2.28 on 2022-08-12 11:05

from django.db import migrations, models
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220710_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packing_video',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number_id',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sid', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=7, prefix='', unique=True)),
                ('tracking_number_id', models.CharField(blank=True, max_length=255, null=True)),
                ('packing_video', models.FileField(blank=True, null=True, upload_to='orders/videos')),
                ('file', models.FileField(blank=True, null=True, upload_to='orders/invoices')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('orders', models.ManyToManyField(to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
