# Generated by Django 2.2.28 on 2022-08-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='matching_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order'),
        ),
    ]
