# Generated by Django 2.2.28 on 2022-09-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220815_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unmatched', 'Unmatched'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=32),
        ),
    ]
