# Generated by Django 2.2.28 on 2022-09-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220905_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='orders',
            field=models.ManyToManyField(related_name='invoices', to='orders.Order'),
        ),
    ]
