# Generated by Django 2.2.28 on 2023-05-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20230321_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unmatched', 'Unmatched'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=32),
        ),
    ]
