# Generated by Django 2.2.28 on 2023-05-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20230514_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sid',
        ),
    ]
