# Generated by Django 2.2.28 on 2024-01-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_order_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unmatched', 'Unmatched'), ('Unmatched_Reservation', 'Unmatched Reservation'), ('Pending', 'Pending'), ('Pending_Reservation', 'Pending Reservation'), ('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=32),
        ),
    ]
