# Generated by Django 2.2.28 on 2022-08-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220710_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_variance',
            field=models.CharField(choices=[('S M L', 'S M L'), ('S M L XL', 'S M L XL'), ('XS S M L XL', 'XS S M L XL'), ('XXS XS S M L XL', 'XXS XS S M L XL'), ('XL XXL XXL', 'XL XXL XXXL'), ('1 3 5 7 9 11 13', '1 3 5 7 9 11 13'), ('0 1 3 5 7 9 11 13', '0 1 3 5 7 9 11 13'), ('14 16 18 20 22', '14 16 18 20 22')], default='2S 2M 2L', max_length=32),
        ),
    ]
