# Generated by Django 2.2.28 on 2022-08-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220812_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterField(
            model_name='product',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
