# Generated by Django 2.2.28 on 2022-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220830_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_variance',
            field=models.CharField(blank=True, default='2S 2M 2L', max_length=255),
        ),
    ]
