# Generated by Django 2.2.28 on 2022-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221003_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sid',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
