# Generated by Django 2.2.28 on 2023-03-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20221003_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='per_item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='per_pack_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
