# Generated by Django 2.2.28 on 2024-03-20 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson', '0003_auto_20240205_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salesperson_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
