# Generated by Django 2.2.28 on 2022-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220625_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='flagged',
            field=models.BooleanField(default=True),
        ),
    ]
