# Generated by Django 2.2.28 on 2024-02-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221002_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SALES_PERSON', 'SALES PERSON')], max_length=50, null=True),
        ),
    ]
